### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'evaluation'

### ISSUE THREAD

**Issue by Zhangky2025** [JinYuanLi0012/PGIM#2]
Hi！ I encountered an error “AttributeError: 'ConfigDict' object has no attribute 'evaluation'” When following Step 4 . Could you tell me how to solve this problem? Thank you so much!

**Comment by JinYuanLi0012** [comment]
Can you provide more error information?

**Comment by Gae-Zhang** [comment]
Thanks! The complete error infomation is as follows:
`Traceback (most recent call last):
  File "***/anaconda3/envs/pytorch3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "***/anaconda3/envs/pytorch3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "***/adaseq/scripts/train.py", line 38, in <module>
    train_model_from_args(args)
  File "***/adaseq/adaseq/commands/train.py", line 94, in train_model_from_args
    checkpoint_path=args.checkpoint_path,
  File "***/adaseq/adaseq/commands/train.py", line 165, in train_model
    trainer.train(checkpoint_path)
  File "***/adaseq/adaseq/training/default_trainer.py", line 146, in train
    return super().train(checkpoint_path=checkpoint_path, *args, **kwargs)
  File "***/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 687, in train
    self.train_loop(self.train_dataloader)
  File "***/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 1219, in train_loop
    self.invoke_hook(TrainerStages.after_train_epoch)
  File "***/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 1371, in invoke_hook
    getattr(hook, fn_name)(self)
  File "***/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/modelscope/trainers/hooks/evaluation_hook.py", line 54, in after_train_epoch
    self.do_evaluate(trainer)
  File "***/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/modelscope/trainers/hooks/evaluation_hook.py", line 67, in do_evaluate
    eval_res = trainer.evaluate()
  File "***/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 768, in evaluate
    self.eval_dataloader = self.get_eval_data_loader()
  File "***/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/modelscope/trainers/trainer.py", line 931, in get_eval_data_loader
    default_config.update(self.cfg.evaluation.get('dataloader', {}))
  File "***/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/modelscope/utils/config.py", line 296, in __getattr__
    return getattr(self._cfg_dict, name)
  File "***/anaconda3/envs/pytorch3.7/lib/python3.7/site-packages/modelscope/utils/config.py", line 55, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'evaluation'`

**Comment by Zhangky2025** [comment]
Thanks! The complete error infomation is as follows:
![图片](https://github.com/JinYuanLi0012/PGIM/assets/55022685/7d2a7704-112e-4432-9281-47f8aa444683)

**Comment by JinYuanLi0012** [comment]
I suspect this situation may be related to [this](https://github.com/JinYuanLi0012/PGIM/blob/57c5eb85ad98cd87ce7d6c9325338dbea6143af4/adaseq/models/base.py#L162-L164). I think it may work if you comment out line162-164.
